" Enable syntax highlighting.
syntax on

" Enable line numbers.
set nu

" Enable column numbers.
set ruler

" Disable arrow keys.
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>
imap <up> <nop>
imap <down> <nop>
imap <left> <nop>
imap <right> <nop>

" Remap <tab> to <esc>
inoremap <tab> <esc>

" Indent using 2 spaces.
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2

" Automatically indent.
filetype plugin indent on
set autoindent

" Remember the last editing position
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" Override the python syntax file's intend settings.
let g:python_recommended_style = 0

" Set the view type for the internal file system explorer.
let g:netrw_liststyle = 3

" Turn on plugins for the detected file type
filetype plugin on

" Set the filetype for VueJS files to HTML.
autocmd BufNewFile,BufRead *.vue set filetype=html

" Set the filetype for MJML files to HTML.
autocmd BufNewFile,BufRead *.mjml set filetype=html

" Set the filetype for *.BUILD files to bazel BUILD.
autocmd BufNewFile,BufRead *.BUILD set filetype=bzl

" Set the filetype for *rc files to vim.
autocmd BufNewFile,BufRead *rc set filetype=vim

" Highlight text over 80 chars
highlight OverLength ctermbg=red ctermfg=white guibg=#592929
match OverLength /\%81v.\+/

" Add skeletons for common extensions.
augroup templates
  autocmd BufNewFile *.vue 0r ~/.vim/templates/skeleton.vue
augroup END

" Increase copy buffer as per https://stackoverflow.com/a/3676914
set viminfo='100,<1000,s100,h
